padre(ramon,geronimo).
padre(ramon,rita).
padre(ramon,rosa).
padre(ramon,rafael).
madre(trinidad,geronimo).
madre(trinidad,rita).
madre(trinidad,rosa).
madre(trinidad,rafael).
padre(german,german).
padre(german,maria).
padre(german,alejandra).
padre(german,ramona).
padre(german,ines).
padre(german,enrique).
padre(german,juan).
padre(german,pedro).
madre(francisca,german).
madre(francisca,maria).
madre(francisca,alejandra).
madre(francisca,ramona).
madre(francisca,ines).
madre(francisca,enrique).
madre(francisca,juan).
madre(francisca,pedro).
padre(geronimo,pilar).
padre(geronimo,estela).
padre(geronimo,omar).
padre(geronimo,javier).
madre(ines,pilar).
madre(ines,estela).
madre(ines,omar).
madre(ines,javier).
abuelo(Abuelo,Nieto):-padre(Abuelo,Padre),padre(Padre,Nieto).
hermano(Hermano,Hijo):-padre(Padre,Hermano),padre(Padre,Hijo),not(Hermano=Hijo).
tio(Hermano,Hijo):-hermano(Hermano,Padre),padre(Padre,Hijo)

